### PR TITLE
fix: ensure form controls are properly checked before setting values

### LINKED ISSUE #261: [Bug]:  SENTRY BUG on all certificate  page
### Description of the bug

 Getting a type error `Cannot read properties of undefined (reading 'setValue')` when trying to see certificate

The stack trace indicates a TypeError (Cannot read properties  of undefined (reading 'setValue')) response from the  
`https://stage-portal.drecs.org/All_certificate` which is Unhandled
### Steps To Reproduce

- Login as an a buyer
- Inspect the page in the network tab
- Go to all certificate  navigation link 
- You will see the error being sent to the sentry

### What environment are you seeing the problem on?

Staging

### What Operating System(OS) are you seeing the problem on?

Linux

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by divinecharlotte**
### SENTRY BUG on all certificate page

Getting a type error Cannot read properties of undefined (reading 'setValue') when trying to set values to null
### How to test this 
- Try to view certificates as a buyer
- Select a value on each select option

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

### CODE REVIEW

**Review by Kingcedru — CHANGES_REQUESTED** [review]
There are many form controls under the `checkFormValidity` method that use setValue. Could you check if they aren't causing any issues?

**Comment by divinecharlotte** [comment]
> There are many form controls under the `checkFormValidity` method that use setValue. Could you check if they aren't causing any issues?

what was causing that was the deviceIds array and organizationName

**Review by Kingcedru — CHANGES_REQUESTED** [review]
The implement solved the setValue error but also caused another one. `can not read properties of null`

**Review by Kingcedru — APPROVED** [review]

File: src/app/view/certificate-details/certificate-details.component.ts [hunk 1]
```diff
@@ -134,8 +134,8 @@ export class CertificateDetailsComponent {
       start_date: [null],
       end_date: [null],
       deviceIds: [],
-      // fromAmountread: [null],
-      // toAmountread: [null],
+      fromAmountread: [null],
+      toAmountread: [null],
```
Comment (musayann) [inline src/app/view/certificate-details/certificate-details.component.ts:138]: these were uncommented by no value was assigned to them

**Review by musayann — CHANGES_REQUESTED** [review]

File: src/app/view/certificate-details/certificate-details.component.ts (hunk 1 above)
Comment (musayann) [reply src/app/view/certificate-details/certificate-details.component.ts:138]: they weren't used

Comment (divinecharlotte) [reply src/app/view/certificate-details/certificate-details.component.ts:138]: @musayann  On the rest ( ) method on line 392 it was throwing an error `TypeError: Cannot read properties of undefined (reading 'setValue')` due to the way  they were  trying to call the setValue method on an object that is undefined, I initialized them to avoid that

**Review by musayann — APPROVED** [review]
