### PR TITLE
fix: user role permissions

### LINKED ISSUE #225: Bug: User Role Permission Submission Without selecting userRole Causes Internal Server Error
### Description
When submitting permissions without selecting a user role, the system returns an "Internal Server Error" instead of displaying a popup reminding the user to select a role.

### Environment

- Operating System: Windows 10

- Browser and version: Google Chrome 127.0

### Expected Behaviour
The system should display a popup reminding the user to select a user role before submission.

### Actual Behaviour
An "Internal Server Error" is displayed when permissions are submitted without selecting a user role.

### Steps to Reproduce

- Navigate to the User Role Permission page.

- Check the required permission without selecting a user role.

- Click the "Submit" button.

### Screenshots or Attachments

Image

### PR DESCRIPTION
**Pull request by Kingcedru**
### Describe your changes

- Fixed internal server Error when user role is not selected.

### Ticket issue

- #225 

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

### CODE REVIEW

**Review by divinecharlotte — DISMISSED** [review]

File: src/app/view/permission/add-userpermission/add-userpermission.component.ts [hunk 1]
```diff
@@ -147,8 +147,16 @@ export class UserpermissionComponent {
       module.selectedPermissions.splice(index, 1);
     }
   }
-  onSubmit(): void {
+  onSubmit(): any {
     if (this.selection.selected.length > 0) {
+      if (
+        typeof this.UserPermissionForm.controls['entityId'].value !== 'number'
```
Comment (musayann) [inline src/app/view/permission/add-userpermission/add-userpermission.component.ts]: what value does it have when empty ? can't we check for being empty or parse the value to check if it's not a number string

**Review by musayann — CHANGES_REQUESTED** [review]

File: src/app/view/permission/add-userpermission/add-userpermission.component.ts (hunk 1 above)
Comment (Kingcedru) [reply src/app/view/permission/add-userpermission/add-userpermission.component.ts]: The value and the type when empty are:
type: object
 value: [ƒ]0: ƒ required(control)length: 1[[Prototype]]: Array(0)

**Review by musayann — APPROVED** [review]
