### PR TITLE
bg: phone number validation

### LINKED ISSUE #298: [Bug]:  Phone number validation on the UI doesn't validate all country codes.
### Description of the bug

- Phone number validation on the UI doesn't validate all country codes, and the gap between the email and phone number input is big.

Image

### Steps To Reproduce

- Navigate to register router
- Type your phone number in the phone number input field.

### What environment are you seeing the problem on?

Dev

### What Operating System(OS) are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by Kingcedru**
### Describe your changes

- Fixed the validation of the phone number to support all country codes.

### Issue ticket number and link

- #298 

### Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.
- [x] The code style guideline have been followed
- [x] Documentation has been updated to reflect your changes.

### CODE REVIEW

**Review by divinecharlotte — DISMISSED** [review]

File: src/app/view/register/register.component.ts [hunk 1]
```diff
@@ -180,87 +180,96 @@ export class RegisterComponent implements OnInit {
...
-                  sessionStorage.setItem('loginuser', JSON.stringify(jwtObj));
-                  //var obj = JSON.parse(sessionStorage.loginuser);
+    const formValues = { ...this.registerForm.value };
+    if (formValues.phoneNumber) {
+      formValues.phoneNumber = this.removePhoneNumberSpaces(
+        formValues.phoneNumber,
+      );
+    }
+    this.authService.PostAuth('user/register', formValues).subscribe({
+      next: (data) => {
```
Comment (musayann) [inline src/app/view/register/register.component.ts:196]: can you refactor this function to use early returns and divide it into reusable functions thus removing the use of else

**Review by musayann — CHANGES_REQUESTED** [review]

**Review by musayann — APPROVED** [review]
